export const CustTypeOptions = {
    options: [
        { name: 'ARCHITECT', id: 1 },
        { name: 'CUNSULTANT/LAB', id: 2 },
        { name: 'RESTORATION CONTRACTOR', id: 3 },
        { name: 'GENERAL CONTRACTOR', id: 4 },
        { name: 'HVAC', id: 5 },
        { name: 'INSURANCE IND.', id: 6 },
        { name: 'PRIVATE/PUBLIC ENTITIES', id: 7 },
        { name: 'PROPERTY MGMT.', id: 8 },
        { name: 'REAL ESTATE IND.', id: 9 },
        { name: 'SCHOOL', id: 10 },
        { name: 'OTHER', id: 11 },
    ]
};

export const JobAndWorkType = {
    options: [
        { name: 'ASBESTOS', id: 1 },
        { name: 'BIOHAZARD - TRAUMA CLEANUP', id: 2 },
        { name: 'CEILING (ACOUST)', id: 3 },
        { name: 'DEMO (CEILING)', id: 4 },
        { name: 'DEMO (WALLS)', id: 5 },
        { name: 'DEMO (OTHER)', id: 6 },
        { name: 'DRYWALL', id: 7 },
        { name: 'EMERGENCY SERVICES', id: 8 },
        { name: 'ENCAPSULATION', id: 9 },
        { name: 'FIREPROOFING', id: 10 },
        { name: 'HVAC SYSTEM', id: 11 },
        { name: 'LEAD', id: 12 },
        { name: 'LINOLEUM', id: 13 },
        { name: 'MASTIC', id: 14 },
        { name: 'METH LAB CLEANUP', id: 15 },
        { name: 'MICROBIAL', id: 16 },
        { name: 'PIPING ROOFING', id: 17 },
        { name: 'STUCCO', id: 18 },
        { name: 'TANK/BOILERS', id: 19 },
        { name: 'TESTING', id: 20 },
        { name: 'TRANSIT ROOFING', id: 21 },
        { name: 'TRANSIT SIDING', id: 22 },
        { name: 'TRANSIT VENT PIPE', id: 23 },
        { name: 'VAT TILE', id: 24 },
        { name: 'OTHER', id: 25 },
    ]
};

export const USStateOptions = {
    options: [
        { name: 'Alabama', id: 1 },
        { name: 'Alaska', id: 2 },
        { name: 'Arizona', id: 3 },
        { name: 'Arkansas', id: 4 },
        { name: 'California', id: 5 },
        { name: 'Colorado', id: 6 },
        { name: 'Connecticut', id: 7 },
        { name: 'Delaware', id: 8 },
        { name: 'Florida', id: 9 },
        { name: 'Georgia', id: 10 },
        { name: 'Hawaii', id: 11 },
        { name: 'Idaho', id: 12 },
        { name: 'Illinois', id: 13 },
        { name: 'Indiana', id: 14 },
        { name: 'Iowa', id: 15 },
        { name: 'Kansas', id: 16 },
        { name: 'Kentucky', id: 17 },
        { name: 'Louisiana', id: 18 },
        { name: 'Maine', id: 19 },
        { name: 'Maryland', id: 20 },
        { name: 'Massachusetts', id: 21 },
        { name: 'Michigan', id: 22 },
        { name: 'Minnesota', id: 23 },
        { name: 'Mississippi', id: 24 },
        { name: 'Missouri', id: 25 },
        { name: 'Montana', id: 26 },
        { name: 'Nebraska', id: 27 },
        { name: 'Nevada', id: 28 },
        { name: 'New Hampshire', id: 29 },
        { name: 'New Jersey', id: 30 },
        { name: 'New Mexico', id: 31 },
        { name: 'New York', id: 32 },
        { name: 'North Carolina', id: 33 },
        { name: 'North Dakota', id: 34 },
        { name: 'Ohio', id: 35 },
        { name: 'Oklahoma', id: 36 },
        { name: 'Oregon', id: 37 },
        { name: 'Pennsylvania', id: 38 },
        { name: 'Rhode Island', id: 39 },
        { name: 'South Carolina', id: 40 },
        { name: 'South Dakota', id: 41 },
        { name: 'Tennessee', id: 42 },
        { name: 'Texas', id: 43 },
        { name: 'Utah', id: 44 },
        { name: 'Vermont', id: 45 },
        { name: 'Virginia', id: 46 },
        { name: 'Washington', id: 47 },
        { name: 'West Virginia', id: 48 },
        { name: 'Wisconsin', id: 49 },
        { name: 'Wyoming', id: 50 },
    ]
};

export const UsProcedure = {
    options: [
        { name: '1', id: 1 },
        { name: '2', id: 2 },
        { name: '3', id: 3 },
        { name: '4', id: 4 },
        { name: '5', id: 5 }
    ]
}